apiVersion: apps/v1
kind: Deployment
metadata:
  name: subdomain-demo
  namespace: f-test
spec:
  selector:
    matchLabels:
      app: subdomain
  template:
    metadata:
      labels:
        app: subdomain
    spec:
      containers:
      - name: subdomain
        image: bhautikchudasama/subdomain:success # {"$imagepolicy": "fluxcd:subdomain-image-repo-policy"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
