apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: subdomain-image-repo
  namespace: fluxcd
spec:
  image: ttl.sh/bhtk-subdomain
  interval: 1m0s

---

apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: subdomain-image-repo-policy
  namespace: fluxcd
spec:
  imageRepositoryRef:
    name: subdomain-image-repo
  filterTags:
    pattern: '^.+-[a-f0-9]+-(?P<ts>[0-9]+)'
    extract: '$ts'
  policy:
    numerical:
      order: asc
