apiVersion: apps/v1
kind: Deployment
metadata:
  name: subdomain-demo
  namespace: test-ns
spec:
  selector:
    matchLabels:
      app: test-ns
  template:
    metadata:
      labels:
        app: test-ns
    spec:
      containers:
      - name: subdomain
        image: bhautikchudasama/subdomain:success
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
